# Generated by Django 4.2 on 2023-04-20 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shield', models.ImageField(upload_to='shields/')),
                ('foundationDate', models.DateField()),
                ('league', models.CharField(choices=[('LaLiga', 'Spanishleague'), ('Premier League', 'Englishleague'), ('Ligue 1', 'Frenchleague'), ('Serie A', 'Italianleague'), ('Bundesliga', 'Germanleague')], default='-', max_length=16)),
                ('actualPosition', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('pastPosition', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dorsal', models.IntegerField()),
                ('goodLeg', models.CharField(choices=[('Zurdo', 'Leftfooted'), ('Diestro', 'Rightfooted'), ('Ambidiestro', 'Bothfeet')], default='-', max_length=12)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='players', to='api.team')),
            ],
            options={
                'unique_together': {('dorsal', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minute', models.IntegerField(validators=[django.core.validators.MaxValueValidator(120)])),
                ('type', models.CharField(choices=[('De cabeza', 'Head'), ('Penalti', 'Penalty'), ('Tiro libre', 'Freeshot'), ('Corner', 'Corner'), ('Chilena', 'Chilean'), ('Pierna izquierda', 'Leftleg'), ('Pierna derecha', 'Righleg')], default='-', max_length=20)),
                ('assistant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assists', to='api.player')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals_conceded', to='api.team')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Champions League', 'Champions'), ('Europa League', 'Europe'), ('LaLiga', 'Spanishleague'), ('Copa del rey', 'Kingcup'), ('Premier League', 'Englishleague'), ('Community shield', 'Community'), ('Ligue 1', 'Frenchleague'), ('Coupe de la Ligue', 'Coupe'), ('Serie A', 'Italianleague'), ('Coppa Italia', 'Coppa'), ('Bundesliga', 'Germanleague'), ('DFB-Pokal', 'Germancope')], default='-', max_length=25)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1888), django.core.validators.MaxValueValidator(2023)])),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='titles', to='api.team')),
            ],
            options={
                'unique_together': {('name', 'year'), ('name', 'team', 'year')},
            },
        ),
    ]
