# Generated by Django 4.2 on 2023-04-20 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goal',
            unique_together={('player', 'team', 'year', 'competition', 'minute')},
        ),
    ]
