# Generated by Django 4.2 on 2023-04-20 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gamesPlayed',
            field=models.IntegerField(default=0),
        ),
    ]
